import AuthButton from "@/components/AuthButton/AuthButton";
import AuthProvider from "@/ctx/Auth";
import { Providers } from "@/ctx/Provider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <Providers session={session}>
        <AuthProvider session={session}>
          <body className={inter.className}>
            {children}
            <AuthButton />
          </body>
        </AuthProvider>
      </Providers>
    </html>
  );
}
